### PR TITLE
Split numbers

### PR DESCRIPTION
**Pull request by cabo**
(Via Joe Hildebrand)

### CODE REVIEW

**Comment by hildjj** [comment]
I don't think this is terribly necessary if we believe the tools to handle all of those formats in one pass are readily available.  If we are going to make the change, I suggest that the hexfloat bits might want to be a separate rule also, since those are likely to need completely separate processing from the hexints.

**Comment by cabo** [comment]
In the case of my implementation, I now have very simple, if somewhat repetitive (on the level of a few tokens), code.
It now seems really hard to get this wrong...

**Comment by cabo** [comment]
(There is indeed a trade-off between making the ABNF best for explaining the syntax and making it most useful as a ready-cut code base for implementers.
I think in this case we have eat the cake and have it, too.)

**Comment by hildjj** [comment]
I think how you have it here is much easier to read.  WFM, thanks.

**Review by hildjj — APPROVED** [review]

**Pull request merged**
